#ifndef _PC5J48M0RPLH5JKYMMM8L6D1OYJOPSXFI2OMJIPUIYK6KENE4W1SJSG9               
#define _PC5J48M0RPLH5JKYMMM8L6D1OYJOPSXFI2OMJIPUIYK6KENE4W1SJSG9

#include <cui/dci/__Role__.h>
#include <cut/cut.h>

CUT_NS_BEGIN

struct Test;

CUI_DEF_ROLE(TestFactory)
{
    CUI_ABSTRACT(Test* make());
};

CUT_NS_END

#endif
